apiVersion: apps/v1
kind: Deployment
metadata:
  name: rjk-deploy
  labels:
    app: rjk-deploy-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rjk-deploy
  template:
    metadata:
      labels:
        app: rjk-deploy
    spec:
      containers:
      - name: jaya-container
        image: jaya002/web-server:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: jaya-service
  labels:
    app: rjk-deploy
spec:
  selector:
    app: rjk-deploy

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8082
    targetPort: 8082
